'use strict';

//=include vendor/jquery-2.2.4.min.js
//=include vendor/underscore-min.js
//=include vendor/ba-tiny-pubsub.min.js
//=include vendor/hammer.min.js
//=include vendor/jquery.hammer.js
//=include vendor/soundmanager2-nodebug-jsmin.js
//=include vendor/clusterfck-0.1.js
//=include vendor/synaptic.js
//=include util.js
//=include player.js
//=include cord.js
//=include chord.js
//=include creature.js
//=include environment.js
//=include node.js
//=include analyzer.js
//=include trainer.js
//=include debug.js
